### ISSUE TITLE
No way to change the back button of nested folders

### ISSUE THREAD

**Issue by techh10** [BarRaider/streamdeck-foldereditor#5]
When you go in a folder, it starts the process for changing the back button, but I want to go one level deeper and change the back button of a folder inside of another folder, and theoretically in the future, a folder inside a folder inside a folder

**Comment by BarRaider** [comment]
While this is not currently possible, you can COPY the nested folder to a top-level profile, modify it, and then copy it back.

**Comment by techh10** [comment]
That worked! thanks!
